### ISSUE TITLE
Are we primarily using this other repo?

### ISSUE THREAD

**Issue by brentxu** [b-harvest/Liquidity-Module-For-the-Hub#1]
https://github.com/tendermint/liquidity

**Comment by Hyung-bharvest** [comment]
yes. we are now using the liquidity repository under tendermint!
https://github.com/tendermint/liquidity

current spec doc can be found at https://github.com/tendermint/liquidity/tree/develop/x/liquidity/spec

general explainer can be found at https://github.com/tendermint/liquidity/tree/develop/doc
